import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CodeQuest',
  description: 'Generated by Abhishek Sharma',
    verification: {
        google: "eT97O8rV5cJiUo09J-B6BLiGJW4S9vr485NXFnOYL2Q",
    },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
